application-form:
  version: 1.x
  css:
    # В отличии от js, тут имеется дополнительное вложение, которое может
    # принимать следующие занчения:  base, layout, component, state and theme
    # В соответствии с SMACSS стандартом они объявляют вес стилей. Соответственно
    # стили с меньшим весом грузятся раньше, а с большим, в самом конце.
    # base CSS_BASE = -200
    # layout  CSS_LAYOUT = -100
    # component  CSS_COMPONENT = 0;
    # state CSS_STATE = 100
    # theme CSS_THEME = 200
    # Если не понимаете, лучше не рискуйте, используйте theme раздел.
    theme:
      # Непосредственно сам файл стилей относительно модуля/темы.
      css/application-form.css: {}
  # js - раздел для объявления JavaScript файлов. Тут всё проще. (опционально)
#  js:
#    # Подключение файла относительно модуля/темы.
#    js/application-form.js: {}