<?php

function application_theme($existing, $type, $theme, $path) {
    return array(
        'form_page' => array(
            'variables' => array(
                'data' => NULL,
            ),
        ),
        'preview_page' => array(
            'variables' => array(
                'data' => NULL,
            ),
        ),
    );
}

function application_page_attachments(array &$attachments) {
    $attachments['#attached']['library'][] = 'application/application-form';
}